import { test, expect } from "@playwright/test";
import { randomUUID } from "node:crypto";

const gateway = process.env.TEST_GATEWAY_URL!;
const platform = "http://localhost:13001";
const admin = "http://localhost:13002";

test("admin results and cancellation update the player's history and wallet", async ({ browser, request }) => {
  const adminLogin = await request.post(`${gateway}/auth/login`, { data: { email: "admin@integration.test", password: "integration-only-admin-password-123" } });
  expect(adminLogin.ok()).toBeTruthy();
  const adminToken = (await adminLogin.json()).accessToken;
  const headers = { Authorization: `Bearer ${adminToken}` };
  const email = `browser-${randomUUID()}@example.test`;
  const password = "browser-test-password-123";
  expect((await request.post(`${gateway}/auth/register`, { data: { email, password, displayName: "Browser Player" } })).ok()).toBeTruthy();
  const playerLogin = await request.post(`${gateway}/auth/login`, { data: { email, password } });
  const playerToken = (await playerLogin.json()).accessToken;
  await request.post(`${gateway}/wallet/me/earn`, { data: { reason: "daily_login" }, headers: { Authorization: `Bearer ${playerToken}` } });
  async function createMarket(title: string) {
    const response = await request.post(`${gateway}/markets`, { headers, data: { title, eventStartAt: new Date(Date.now() + 3_600_000).toISOString(), outcomes: ["Home", "Away"] } });
    expect(response.ok()).toBeTruthy(); return response.json();
  }
  const title = `Browser match ${randomUUID().slice(0, 6)}`;
  const item = await createMarket(title);
  const playerContext = await browser.newContext();
  const adminContext = await browser.newContext();
  const playerPage = await playerContext.newPage();
  const adminPage = await adminContext.newPage();
  const errors: string[] = [];
  playerPage.on("pageerror", error => errors.push(error.message));
  adminPage.on("pageerror", error => errors.push(error.message));
  await adminPage.goto(`${admin}/login`);
  await adminPage.getByLabel("Email", { exact: true }).fill("admin@integration.test");
  await adminPage.getByLabel("Password", { exact: true }).fill("integration-only-admin-password-123");
  await adminPage.getByRole("button", { name: "Sign in", exact: true }).click();
  await expect(adminPage.getByRole("heading", { name: "Markets", exact: true })).toBeVisible();
  await playerPage.goto(`${platform}/login`);
  await playerPage.getByLabel("Email", { exact: true }).fill(email);
  await playerPage.getByLabel("Password", { exact: true }).fill(password);
  await playerPage.getByRole("button", { name: "Log in", exact: true }).click();
  await expect(playerPage.getByRole("button", { name: "Log out" })).toBeVisible();
  await playerPage.goto(`${platform}/markets/${item.id}`);
  await playerPage.getByRole("combobox", { name: "Outcome", exact: true }).selectOption(item.outcomes[0].id);
  await playerPage.getByLabel("Amount", { exact: true }).fill("10");
  await playerPage.getByRole("button", { name: "Stake", exact: true }).click();
  await expect(playerPage.getByRole("status")).toContainText("Staked 10 coins");
  await playerPage.getByRole("link", { name: "My predictions", exact: true }).click();
  const card = playerPage.locator("article").filter({ hasText: title });
  await expect(card).toContainText("Awaiting result");
  const row = adminPage.getByRole("row").filter({ hasText: title });
  await row.getByRole("button", { name: "Lock", exact: true }).click();
  await row.getByLabel(`Resolution for ${title}`).selectOption(item.outcomes[0].id);
  await row.getByLabel(`Evidence for ${title}`).fill("Verified browser scorecard");
  await row.getByRole("button", { name: "Record result and pay" }).click();
  await expect(row.locator("span").filter({ hasText: /^settled$/ })).toBeVisible();
  await expect(card).toContainText("Won");
  await expect(card).toContainText("10 coins returned");
  await expect(playerPage.getByText("50 coins", { exact: true })).toBeVisible();

  const cancelTitle = `Cancelled browser match ${randomUUID().slice(0, 6)}`;
  const cancelled = await createMarket(cancelTitle);
  await playerPage.goto(`${platform}/markets/${cancelled.id}`);
  await playerPage.getByRole("combobox", { name: "Outcome", exact: true }).selectOption(cancelled.outcomes[0].id);
  await playerPage.getByLabel("Amount", { exact: true }).fill("7");
  await playerPage.getByRole("button", { name: "Stake", exact: true }).click();
  await expect(playerPage.getByRole("status")).toContainText("Staked 7 coins");
  await adminPage.reload();
  await expect(adminPage.getByRole("heading", { name: "Markets", exact: true })).toBeVisible();
  const cancelledRow = adminPage.getByRole("row").filter({ hasText: cancelTitle });
  await cancelledRow.getByLabel(`Evidence for ${cancelTitle}`).fill("Rain abandonment");
  await cancelledRow.getByRole("button", { name: "Cancel and refund", exact: true }).click();
  await expect(cancelledRow.locator("span").filter({ hasText: /^cancelled$/ })).toBeVisible();
  await playerPage.goto(`${platform}/predictions`);
  await expect(playerPage.locator("article").filter({ hasText: cancelTitle })).toContainText("Refunded");
  await expect(playerPage.getByText("50 coins", { exact: true })).toBeVisible();

  await adminPage.goto(`${admin}/branding`);
  const brandName = adminPage.getByLabel("Brand name", { exact: true });
  await expect(brandName).toBeVisible();
  const originalName = await brandName.inputValue();
  const originalFont = await adminPage.getByRole("combobox", { name: "Font", exact: true }).inputValue();
  await brandName.fill("Browser Cricket");
  await adminPage.getByRole("combobox", { name: "Font", exact: true }).selectOption("Nunito");
  await adminPage.getByRole("button", { name: "Save theme", exact: true }).click();
  await expect(adminPage.getByText("Theme saved — reload the player app to see it.")).toBeVisible();
  await playerPage.reload();
  await expect(playerPage.getByRole("img", { name: "Browser Cricket", exact: true })).toBeVisible();
  await expect.poll(() => playerPage.evaluate(() => document.documentElement.style.getPropertyValue("--font-display-active"))).toContain("--font-nunito");
  await brandName.fill(originalName);
  await adminPage.getByRole("combobox", { name: "Font", exact: true }).selectOption(originalFont);
  await adminPage.getByRole("button", { name: "Save theme", exact: true }).click();
  await expect(adminPage.getByText("Theme saved — reload the player app to see it.")).toBeVisible();
  await adminPage.getByRole("link", { name: "Operations", exact: true }).click();
  await expect(adminPage.getByRole("heading", { name: "Operations", exact: true })).toBeVisible();
  await expect(adminPage.getByText("No pending coin transfers.", { exact: true })).toBeVisible();
  await expect(adminPage.getByText("No results awaiting completion.", { exact: true })).toBeVisible();
  await adminPage.route("**/operations/settlement?*", route => route.fulfill({ status: 503, contentType: "application/json", body: '{"error":"Unavailable"}' }));
  await adminPage.getByRole("button", { name: "Refresh", exact: true }).click();
  await expect(adminPage.getByRole("alert").filter({ hasText: "Cannot refresh recovery backlog" })).toBeVisible();
  await adminPage.unroute("**/operations/settlement?*");
  await adminPage.reload();
  await expect(adminPage.getByRole("heading", { name: "Operations", exact: true })).toBeVisible();
  expect(errors).toEqual([]);
  await playerContext.close(); await adminContext.close();
});
