<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MarketCatalog.Application\MarketCatalog.Application.csproj" />
    <ProjectReference Include="..\MarketCatalog.Infrastructure\MarketCatalog.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="../../shared/DatabaseStartup.cs" Link="Configuration/DatabaseStartup.cs" />
    <Compile Include="../../shared/ProductionConfiguration.cs" Link="Configuration/ProductionConfiguration.cs" />
  </ItemGroup>
</Project>
